### ISSUE TITLE
What do I need to do for face photos before testing?

### ISSUE THREAD

**Issue by ghost** [adobe-research/AutoToon#1]
What are the requirements for input photos?
e.g. size, rendering, illumination, file size and so on........

**Comment by soravux** [comment]
The `test.py` script will automatically perform any required resizing and face alignment.
More specifically, face alignment is performed at [this line](https://github.com/adobe-research/AutoToon/blob/master/test.py#L87) and resizing at [this line](https://github.com/adobe-research/AutoToon/blob/435aa36bdfe3de243f296ee70cbb4403b0889e44/test_utils.py#L118).

The model should be relatively tolerant to most common white-balanced illuminations that are dominated by ambient or uniform lighting (i.e., no strong cast shadow or visible lighting patterns on the face).

There is no requirement on file size. Any RGB file that can be [open by PIL/pillow](https://pillow.readthedocs.io/en/stable/handbook/image-file-formats.html?highlight=file%20formats#image-file-formats) should work fine.
